CREATE TABLE "chat_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"missionId" integer NOT NULL,
	"senderId" integer NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "custody_steps" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "custody_steps_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"missionId" integer NOT NULL,
	"correspondentId" integer NOT NULL,
	"description" varchar(500) NOT NULL,
	"photoUrl" text,
	"latitude" real,
	"longitude" real,
	"locationName" varchar(255),
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deleted_accounts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deleted_accounts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"openId" varchar(64) NOT NULL,
	"deletedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mission_applications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mission_applications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"missionId" integer NOT NULL,
	"correspondentId" integer NOT NULL,
	"message" text,
	"status" varchar DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mission_assistance_guidance" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mission_assistance_guidance_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assistanceRequestId" integer NOT NULL,
	"senderId" integer NOT NULL,
	"content" varchar(1000) NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mission_assistance_requests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mission_assistance_requests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"missionId" integer NOT NULL,
	"requesterId" integer NOT NULL,
	"recipientId" integer NOT NULL,
	"note" varchar(500),
	"status" varchar DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"respondedAt" timestamp,
	"closedAt" timestamp,
	"expiresAt" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "missions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "missions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"requesterId" integer NOT NULL,
	"correspondentId" integer,
	"title" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"category" varchar(128) DEFAULT 'other' NOT NULL,
	"customCategoryId" integer,
	"customServiceName" varchar(255),
	"customServiceDescription" text,
	"status" varchar DEFAULT 'open' NOT NULL,
	"urgency" varchar DEFAULT 'medium',
	"location" varchar(500) NOT NULL,
	"latitude" real,
	"longitude" real,
	"deadline" timestamp,
	"budget" numeric(10, 2),
	"aiGuidance" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notifications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"body" text NOT NULL,
	"type" varchar NOT NULL,
	"relatedId" integer,
	"isRead" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "push_devices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "push_devices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"expoPushToken" varchar(255) NOT NULL,
	"platform" varchar NOT NULL,
	"deliveryMode" varchar DEFAULT 'remote' NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reviews" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"missionId" integer NOT NULL,
	"reviewerId" integer NOT NULL,
	"revieweeId" integer NOT NULL,
	"reviewerRole" varchar(20) DEFAULT 'requester' NOT NULL,
	"rating" integer NOT NULL,
	"ratingPunctuality" integer,
	"ratingCommunication" integer,
	"ratingQuality" integer,
	"ratingProfessionalism" integer,
	"ratingClarity" integer,
	"ratingPayment" integer,
	"comment" text,
	"isPublic" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "service_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "service_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(64) NOT NULL,
	"name" varchar(128) NOT NULL,
	"description" text,
	"icon" varchar(64) DEFAULT 'briefcase',
	"isBuiltIn" boolean DEFAULT false NOT NULL,
	"isApproved" boolean DEFAULT false NOT NULL,
	"createdBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "service_categories_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "support_messages" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "support_messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ticketId" integer NOT NULL,
	"senderId" integer NOT NULL,
	"content" text NOT NULL,
	"isStaff" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "support_tickets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "support_tickets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"subject" varchar(255) NOT NULL,
	"status" varchar DEFAULT 'open' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"emailVerified" boolean DEFAULT false,
	"passwordHash" varchar(255),
	"phone" varchar(20),
	"phoneVerified" boolean DEFAULT false,
	"googleId" varchar(128),
	"facebookId" varchar(128),
	"appleId" varchar(128),
	"loginMethod" varchar(64),
	"authProvider" varchar DEFAULT 'manus',
	"resetToken" varchar(128),
	"resetTokenExpiry" timestamp,
	"emailVerifyToken" varchar(128),
	"emailVerifyExpiry" timestamp,
	"role" varchar DEFAULT 'user' NOT NULL,
	"userType" varchar DEFAULT 'requester',
	"trustLevel" varchar DEFAULT 'explorer',
	"totalMissions" integer DEFAULT 0,
	"averageRating" real DEFAULT 0,
	"bio" text,
	"avatarUrl" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
